### ISSUE TITLE
model sample error 

### ISSUE THREAD

**Issue by ashleymaeconard** [mackelab/autohmm#31]
When running your small example, the model.sample returns this. Can you tell me what I should do? Also - do you have a place where I can read the background math for your implementation? 

`>>> samples, states = model.sample(n_samples=500)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/data/compbio/aconard/AR/autohmm/autohmm/ar.py", line 595, in sample
    newstate = (transmat_cdf[states[idx-1]] > nrand[idx-1]).argmax()
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

**Comment by balalofernandez** [comment]
did you solve it?

**Comment by balalofernandez** [comment]
just add int(): `newstate = (transmat_cdf[int(states[idx-1])] > nrand[idx-1]).argmax()`
